#
# WLA DX Linux build script (Clang)
#
trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
variables:
  # Setting these at the job level ensures CMake picks them up automatically
  CC: clang
  CXX: clang++
steps:
- script: |
    set -ex
    sudo apt -y update
    sudo apt install -y valgrind clang
  displayName: 'Install Dependencies'
  timeoutInMinutes: 60

- script: |
    make clean
    # Debug build with enhanced warnings to catch uninitialized variables
    cmake -DGDB_DEBUGGING=ON \
          -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_C_FLAGS="-g -Wall -Wextra -Wuninitialized" \
          -DCMAKE_CXX_FLAGS="-g -Wall -Wextra -Wuninitialized" \
          -G "Unix Makefiles"
    make
  displayName: 'Build Debug (Clang)'
  timeoutInMinutes: 60

- script: |
    ./run_tests.sh
  displayName: 'Run Tests (Debug)'
  timeoutInMinutes: 60

- script: |
    make clean
    # Release build with debug symbols for Valgrind + strict warnings
    cmake -G "Unix Makefiles" \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_C_FLAGS="-g -Wall -Wextra -Wuninitialized" \
          -DCMAKE_CXX_FLAGS="-g -Wall -Wextra -Wuninitialized"
    make
  displayName: 'Build Release (Clang) with Debug Symbols'
  timeoutInMinutes: 60

- script: |
    ./run_tests.sh
  displayName: 'Run Tests (Release)'
  timeoutInMinutes: 60
