#
# WLA DX Linux build script (Clang)
#

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Setting these at the job level ensures CMake picks them up automatically
  CC: clang
  CXX: clang++

steps:
- script: |
    set -ex
    sudo apt -y update
    sudo apt install -y valgrind clang
  displayName: 'Install Dependencies'
  timeoutInMinutes: 60

- script: |
    make clean
    # Note: Using your project-specific GDB_DEBUGGING flag as requested
    cmake -DGDB_DEBUGGING=ON -DCMAKE_BUILD_TYPE=Debug -G "Unix Makefiles"
    make
  displayName: 'Build Debug (Clang)'
  timeoutInMinutes: 60

- script: |
    ./run_tests.sh
  displayName: 'Run Tests (Debug)'
  timeoutInMinutes: 60

- script: |
    # Explicitly use Unix Makefiles with Clang
    cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
    make
  displayName: 'Build Release (Clang)'
  timeoutInMinutes: 60

- script: |
    ./run_tests.sh
  displayName: 'Run Tests (Release)'
  timeoutInMinutes: 60
